#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-01-20 Mon 20:48>
#+TITLE: Idea

* 闪念

#+BEGIN_QUOTE
舍，得，是一种生活的艺术。
#+END_QUOTE
** [2020-07-15 三 06:02] - 我会如何死去？                              :Life:
	标题是不是有些意思？这个月我作息不太好，黑白颠倒的，生活状态都是白天12点开始睡觉，晚上6-7就醒来，吃个晚饭后就开始其他人的“白天生活”。这样的作息让我现在的睡眠质量越来越差了，现在的我想要
睡着就必须是到达一个非常困的临界点才能睡着，可能是因为现在的我满脑子都充满了焦虑，心态太急，学什么东西都想求快，这可能是造成了我有时一件事做不好的主要原因吧。
	前两天我做了个梦，梦到自己是突发性去世的，就是因为日夜颠倒，加上我喜欢喝冰水，造成的猝死。其实当时这个梦我睡醒后是记不清的，是昨天白天，大概接近12点时，我感觉很疲惫，但是手头上的事还未作
完，就想着做完再睡吧，就开了罐冰镇饮料，然后我喝了第二口后前几天梦境中的场景就突然从我脑海里浮现出来，我顿时紧张了，害怕了，心态加速了梦，很自然的拿起旁边的香烟点了根烟，刚点完突然意识到，抽烟
不也对身体有害么，赶紧把烟灭了后，跑去洗了把脸就回到床上躺着。
	傍晚7点，我疲惫地醒来，又想到睡前经历的这一切，感觉还好我命大，要不然可能真就如梦里所现的那样死去了。今天是早晨五点醒来的，我又想了想，觉得这个话题还挺有意思，就想着写一篇闪念吧。我还挺希望
可以跟评论区的小伙伴们交流的，不过目前这个博客系统没有评论区支持，如果你想说什么，可以邮箱联系我，主页里有我的联系方式 :)
** [2020-08-12 三 01:14] - 你说你不想看手机                            :Life:
   你说你不想看手机，我认为这都是借口吧，你是不想跟我说话吧？嘴上说着不是，但却是这么做的吧？反正也不可能
被发现的，只要不自爆，死不承认不就行了。既然你喜欢玩，那我就陪你玩玩，看看是谁吃亏。
** [2020-09-04 五 11:07] - 为什么丰都这里有这么多山洞啊！！！          :Life:
   信号也差得不行
** [2020-09-17 四 21:05] - 我无法掩盖想你的心                          :Life:
   我好想你啊!
** [2020-09-20 日 15:43] - 发挥想象力写一篇作文                        :Life:
   突然想到小时候的作文题目，发挥想象力写一篇作文，那时想的都是成为一个什么职业，随后去做什么事，
现在想的都是能挣多少多少钱，如何如何就能轻松的挣钱，果然我随着年龄的攀升是越来越爱做白日梦了。
** [2020-09-22 二 15:07] - 图书馆撑伞                                  :Life:
   咱们广财图书馆有个很有趣的现象，阳光照进图书馆后，大家都会拿伞遮挡住阳光，比起这样，我更愿意让阳光打在我的课本上。
** [2020-09-23 三 10:18] - 看书                                       :Study:
   一句话看不懂，看十遍真的有用么？不如换个角度看呢!
** [2020-09-23 三 19:32] - 杨泽霖                                      :Life:
   杨泽霖说想看我闪念。
** [2020-09-24 四 11:07] - 不是吧                                      :Life:
   不是吧不是吧真的是她么？
** [2020-09-24 四 11:14] - 好吧                                        :Life:
   好吧不是她，看走眼了
** [2020-09-24 四 12:52] - 困                                          :Life:
   昨晚没睡好，导致现在在图书馆里看书有些困。
   说起困这个话题，突然想描述一下困是一种什么感觉。
   困是预示你现在想要睡觉了，有关具体的大脑是如何让人感知到困的我不太了解，但是能描述困的感觉！
   当你感到困的时候，例如你在看书，当你看着看着感到困了，那你肯定专注度不够了，因为困会让你想睡觉，此时你的大脑可能就是在并发执行进程，一个进程在运行着阅读书籍程序，另一个进程就是让你想要睡觉程序，而像阅读书籍这种程序呢它最好是持续运行，否则其利用率就会大大降低，这就是为什么我说当你感到困时你的专注度就肯定会下降的原因了。再具体说一下由困引发的打瞌睡，其实打瞌睡有三种状态：
   - 第一种
	看书占70%而想睡觉占30%，每看小会书就会想睡觉，这时你的阅读书籍进程请求中断，这个中断处理程序的作用是让你不要打瞌睡，此时你就又清醒了一下，调整好姿态准备继续运行阅读书籍程序，是的由于清醒程序的时间片已经用完，坚持不了多久，你就又开始打瞌睡了。
   - 第二种
	 想睡觉占70%，看书占30%，每打一会瞌睡就看一会书，其原理跟第一种打瞌睡差不多，只不过置反了罢了。这种打瞌睡的方式会让你感到一会舒适，一会地狱，就像周末想睡懒觉的你被你妈每隔几分钟来叫醒一趟的你，所以这种方式打瞌睡是最不舒适的，因为书籍也一点都看不下去，睡觉也睡不好，有睡觉内感觉了结果又醒了，简直是太难受了！
   - 第三种
	 这种方式的打瞌睡就是已经眼睛已经完全闭上了，但是脑子里仍然想的是阅读书籍进程，唉可能这就是进程与进程之间的交往性吧~，这种感觉最奇妙，明明你能清晰的感知到自己睡着了，但是却又不想平常睡觉一样的深沉，你就像在醒着睡一样！身边的一切事物你都能感知到，真是神奇不是么？说明我们的大脑真的很强大，至少说其处理能力很强大，虽然是类似单核的CPU，但是其容量真的超大，通过一些碎片就能整理很多成体系的想法出来。可能这种打瞌睡的方式让人很舒服吧，毕竟终于能稍微专注与睡觉了不是么，但是！这种方式在处理打瞌睡进程后，身体会感到异常的疲惫，具体原因暂时未知，我猜想可能是因为打瞌睡本身就是一个优先级较高的进程，而平常睡觉前都会执行的调整睡姿等程序都没有运行的吧。

最后，本来还挺困的，现在突然不困了，从计算机系统的角度来想，当我想要打瞌睡时是不是只需要找一个优先级更高的进程就可以防止我打瞌睡了！但是凡是都有两面性啊，总是做一件事也不太好，毕竟一直写闪念的话那书都不用读了对么？

突然想到...大脑的中的进程是否存在自带程序的进程，这些进程是否比普通进程优先级高，反正目前我能想到的大脑自带进程就是做爱了，只有做爱才能让一切变成串行执行....
** [2020-09-25 五 18:29] - 便便                                        :Life:     
   便便有三种味道:
   - 别人拉的
	 奇臭无比
   - 自己拉时
	 毫无波澜
   - 自己拉完
	 奇臭无比
** [2020-09-26 六 14:45] - 新教徒                                     :Study:
   今天又帮助一位同学安装了ArchLinux，桌面使用的是KDE，希望他能好好用下去吧。
** [2020-09-26 六 15:04] - 彩虹猫                                      :Life:
   在图书馆看书，一直用Emasc播放彩虹猫的歌曲，真的好嗨啊！不过听久了之后甚至会觉得很平静。。
** [2020-09-26 六 15:12] - 擤鼻涕                                      :Life:
   真的是日了狗了，前两天睡觉空调温度太低了，导致我现在有些感冒，疯狂流鼻涕，难受死了。
   关键是我在图书馆啊喂！很尴尬。
** [2020-09-26 六 16:27] - 流鼻涕                                      :Life:
   我很想知道流鼻涕时到底要不要多喝水呢？我感觉多喝水只会让我流鼻涕的量更大!!!!
** [2020-10-07 三 16:36] - 腱鞘炎
   这两天打王者荣耀有些多，导致我的左手小拇指有些腱鞘炎了。
身为一个Emacs用户，居然都没有腱鞘炎，玩个王者荣耀倒是给我整了这一出，真是操蛋... 这说明那些职业选手也是挺难受的。
** [2020-10-12 一 08:29] - 我吐了                                      :Life:
   大三的某老师说话的语调怎么让人那么难受呢？
** [2020-10-16 五 10:32] - 我又来吐槽学校的教学方式了                 :Study:
   今年大三了，学校开了门Python课程，翻了翻书发现书中的知识点我已经全部掌握，但是我还是来听课了。
可笑的是老师在面对已经学了两年计算机课程的同学们却还是将安装Python和PyCharm开发工具讲了三节课，一节课近两小时。
果然教育才是成为百万富翁的道路!!!
** [2020-10-18 日 00:54] - 你与我的区别                                :Life:
   为什么视频时你可以做到你完全做你的事情，把我晾在一边呢？而我却做不到.
** [2020-10-24 六 14:25] - 1024程序员节日快乐!                         :Life:
   希望那些已经在岗位的前辈们今天能轻松些吧1
** [2020-11-11 三 17:40] - 很喜欢404 rapper的一首歌《Freedom》         :Life:
   我也曾困惑也曾贪婪也曾因为入戏太深
   所经历的一切让我失了神
   如果成功的代价先学会怎么冷血无情
   那我可能天生不是成大事的人
   如果生活太忙碌 不要改掉我的懒病
   允许我荷尔蒙释放自由的反应
   如果这世界太多Liar 变得太过复杂现实
   请保留我心中仅存那份感性
   何必呢拐弯抹角 让你自己过的累
   习惯了这种方式 于是灵魂错了位
   当流言蜚语遍布周围 他们问我后不后悔
   我一直觉得自己做得对
** [2020-11-11 三 19:00] - 最远的距离                                  :Life:
   最远的距离可能就是：我问你在干什么，而你却得绞尽脑汁想一件可以让我不要打扰你的事，成为想远离我的说辞。
** [2020-11-11 三 23:27] - 你可以多做自己的事情，不要把我太放在心上    :Life:
   你就是我的全世界，没有你我怎么快乐。
** [2020-11-12 四 01:53] - 关于你                                      :Life:
   你是世上疗效最好的药，在我悲伤时，你的一句话就让我重启至初始状态。
   你又是世上最锋利的剑，拥有钢铁般的内心的我，抵不过你的一句话便宕机。
** [2020-11-15 日 15:01] - JS真难用                                   :Study:
   我一向不喜欢JS，原因就是感觉这个门语言一点都不标准，不仅语法丑，而且坑还多，最恶心的是居然用的人还多，我也是服了。
** [2020-11-16 一 10:56] - 不要不以为然                                :Life:
   学校不允许在教学楼吸烟。但我却不以为然，吸完烟还随地丢烟头。上课时回到教室坐下，无意间往门外一往，原来我丢的烟头被志愿者同学捡起，此时的我惭愧不已。
** [2020-11-17 二 00:09] - 生日快乐!                                   :Life:
   祝自己生日快乐!
** [2020-11-20 Fri 13:41] - 将不开心的和开心的都写下来                 :Life:
   而不是告诉你
** [2020-11-24 Tue 09:27] - 大宝SOD蜜                                  :Life:
** [2020-11-24 Tue 10:14] - 有趣的翻译                                 :Life:
   #+begin_quote JavaScript高级程序设计-4th
   函数也是一种引用类型，但有关函数的内容太多了，一章放不下，所以本书专门用第10章来介绍函数。
   #+end_quote

   我还以为要用>两章的篇幅来讲函数呢。
** [2020-11-24 Tue 14:35] - CSS真的写到我想吐                          :Life:
   害！像我这么笨的人，后端语言学起来吃力，前端技术又嫌麻烦，真是如何是好呀！
** [2020-11-24 Tue 15:47] - 什么方向                                   :Life:
   有些疲惫，不知现在要看什么，感觉非常的浮躁。
** [2020-11-24 Tue 19:11] - 忍耐枯燥，忍耐寂寞                         :Life:
   NULL
** [2020-11-27 Fri 21:23] - 大脑控制了人，还是人控制了大脑             :Life:
   人是由大脑控制，而标题的人是指"具有智慧的你/我/他"，如果人能随意通过大脑控制人体的任何部件或运作方式该多好呀，比如说当你困的时候可能是因为身体分泌了某些物质，从而让你感到疲惫，但是这个是由大脑自身发出的，作为人的你只能接受，无法直接轻易改变。如果你想要改变你就得通过一些外部方式来让大脑被动地激活一些功能，例如你现在可以去洗把脸让自己清醒一会，可真的是一会儿啊，因为如果大脑真的想睡觉，身为人的你是无法控制大脑的。

   这个话题挺有意思，有空来看看。
** [2020-11-28 Sat 12:36] - 心态爆炸怎么办?                            :Life:
   吸气4秒，憋气7秒，吐气8秒。抽根烟。
   什么？你不抽烟？那你就哭吧，哭出来就好了。
** [2020-11-28 Sat 13:23] - 我的情绪真的很差                           :Life:
   我们不是很般配，你的理性比我更加干脆。
** [2020-11-29 Sun 08:23] - 早安!                                      :Life:
   早上好呀，今天也要加油喔!
** [2020-12-01 Tue 19:06] - 大厂的力量                                 :Life:
   由微软开发并开源的LSP协议，是否强大，其原本给予VSCODE使用的，但是其开源，意味着其他编辑器也可以获取其无限接近IDE的对代码的分析能力，从最基本的自动补全，到寻找引用，寻找定义，随后每个不同的编程语言又拥有不同的功能，例如Dart就是一个例子，其除了上面所提到的功能之外还有很多其自身所需的功能，例如跟Flutter交互，利用dap-mode方便得进行调试运行，以及十分方便的进行单元测试，还有一些针对其UI方面能力的扩展。但是反观Python就不一样了，Python有很多LSP插件但是，显然是大家对其不满意又重新造，造完又有人觉得不满意，就又重新造，这么来来回回的没有一个持续的生态发展下去，除了VSCode本身还算不错之外，其他依偎于LSP的编辑器的Python LSP 就没那么舒服了，各种性能差，功能少等问题层出不穷，就是因为没有大厂直接接手，都是由社区的开发者进行维护的，难免技术上，协作能力上都不如大厂统一管理得好，这么说来其实大厂也有大厂的好处，大厂结合开源那对整个技术圈子都是一个不错的结合。
** [2020-12-03 Thu 15:01] - 比较                                       :Life:
   A = 10，B = 20，所以A < B。
   Emacs = emacs-lisp + text-editor, Vim = vimscript + text-editor
   so if emacs-lisp > vimscript then Emacs > VIM = t;
   
   上面这个成立么，当不成立，但是往往人们就是喜欢把问题思考的那么简单。从而犯了叫做比较异常错误。
原本两个事物无法直接进行比较，却硬要进行比较，最后比较出来的结果那肯定是不准确的，如果非要简单的进行思考，其实可以直接从自身属性出发即可，例如。
    #+begin_src javascript
      xiaoming =
          {
              key_style: "HJKL",
              environment: "GNU/Linux",
              text_editor:undefined
              finger_length: 12cm
          }

      if (xiaoming.finger_length >= 12cm){
          xiaoming.text_editor = "Emacs"
      }else if(xiaoming.key_style === "Ctrl,ALT,A-Z"){
          xiaoming.text_editor = "Emacs"
      }else if(xiaoming.environment === "Windows"){
          xiaoming.text_editor = "VSCODE"
      }else{
          xiaoming.text_editor = "Vim"
      }
    #+end_src
** [2020-12-05 Sat 08:14] - 早安!                                      :Life:
   早安！今天也要加油哟！！！为了自己想要的人和物！
** [2020-12-05 Sat 09:19] - 什么情况？                                 :Life:
   连续打了几个哈欠，我这是困了？不应该呀。可能是昨晚睡太晚了(12点睡)，今天早晨我都没有自然醒，平常都是自然醒的。
** [2020-12-06 Sun 08:58] - 早安!                                      :Life:
   早上好!虽然你今天起得比较晚，但是你昨晚睡的很好呀！今天也要努力喔！
** [2020-12-06 Sun 20:39] - 使用Emacs的时候到底需不需要关闭Buffer?     :Life:
   我平常是会关闭Buffer的，可能是早期学习使用Emacs时的习惯，但是现实是最好不要管理它。因为Emacs是一个集大成者。如果非要给Buffer归类可能可以归类好几十种，这时候你再通过一个一个删除，你会感觉到非常的繁琐。所以我觉得改掉这个习惯，从此不关Buffer，反正眼部不见心不烦，有模糊搜索的Counsel-buffer根本不需要关闭。
** [2020-12-08 Tue 08:00] - 早安                                       :Life:
   早安哟~ 天宇，今天你也要继续努力呀！困了就站起来读书，累了就边走边读，拼他个你死我活！认真、专注、思考、快乐。
   让我们珍惜时间一起感受学习的快乐。
** [2020-12-21 Mon 15:31] - 背一万个单词真的有用么？                  :Study:
   我老爸给了我一本书，《向上生长》。老爸给我时说在你迷茫不知方向在哪时可以翻一翻，又简单说了些书中的看法。提到，写一万行代码就能让你编码能力大大提升，我有些不以为然，因为我一直坚信质量比数量更加优先，自以为是个天才。但看了这本书提到的采伐爱心你自己往往是因为这些自以为是的心态而做不好事情，没有肯下笨功夫的心。学任何事物都从先是google如何学习，然后网上看了一大堆，各种各样的说法让我感到更加迷茫，我现在就想为何不尝试一下笨功夫，抛去自以为是的天才理论，持续走下去看看效果如何。
   由于我前些日子写了个shengci插件，正好是满足自己需求的背单词工具，但是我虽然用此工具记录了很多生词，但是没有好好利用其背单词功能，很少练习，所以大量的生词直接摆在我面前使得我更加畏惧了。。。所以我便将所有单词删除，决定重新记忆，这次每天真正开始使用，并且利用emacs的capture捕获使用插件时的灵感方便日后添加插件功能。
** [2021-01-19 Tue 11:19] - Emacs的卡顿让人难受                       :Emacs:
   不知从何时起，Emacs让我越来越讨厌了。原因是我明显感受到Emacs越来越慢了，休眠了一个晚上的电脑唤醒之后，原本的Emacs并没有关闭，随后我的任何操作会变得十分卡顿，十分影响心情和状态。比如当我按撤回时，emacs的垃圾回收就会让Emacs卡顿很久，我只能盯着mini-buffer的Garbage collcetion...并在心里抱怨一句，“Emacs怎么又卡了，真tm垃圾，垃圾回收机制应该叫做，垃圾垃圾回收机制吧！”
   
   
   
