#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-01-20 Mon 20:48>
#+TITLE: Idea

* 闪念

#+BEGIN_QUOTE
舍，得，是一种生活的艺术。
#+END_QUOTE
** [2020-07-15 三 06:02] - 我会如何死去？                              :Life:
	标题是不是有些意思？这个月我作息不太好，黑白颠倒的，生活状态都是白天12点开始睡觉，晚上6-7就醒来，吃个晚饭后就开始其他人的“白天生活”。这样的作息让我现在的睡眠质量越来越差了，现在的我想要
睡着就必须是到达一个非常困的临界点才能睡着，可能是因为现在的我满脑子都充满了焦虑，心态太急，学什么东西都想求快，这可能是造成了我有时一件事做不好的主要原因吧。
	前两天我做了个梦，梦到自己是突发性去世的，就是因为日夜颠倒，加上我喜欢喝冰水，造成的猝死。其实当时这个梦我睡醒后是记不清的，是昨天白天，大概接近12点时，我感觉很疲惫，但是手头上的事还未作
完，就想着做完再睡吧，就开了罐冰镇饮料，然后我喝了第二口后前几天梦境中的场景就突然从我脑海里浮现出来，我顿时紧张了，害怕了，心态加速了梦，很自然的拿起旁边的香烟点了根烟，刚点完突然意识到，抽烟
不也对身体有害么，赶紧把烟灭了后，跑去洗了把脸就回到床上躺着。
	傍晚7点，我疲惫地醒来，又想到睡前经历的这一切，感觉还好我命大，要不然可能真就如梦里所现的那样死去了。今天是早晨五点醒来的，我又想了想，觉得这个话题还挺有意思，就想着写一篇闪念吧。我还挺希望
可以跟评论区的小伙伴们交流的，不过目前这个博客系统没有评论区支持，如果你想说什么，可以邮箱联系我，主页里有我的联系方式 :)
** [2020-08-12 三 01:14] - 你说你不想看手机                            :Life:
   你说你不想看手机，我认为这都是借口吧，你是不想跟我说话吧？嘴上说着不是，但却是这么做的吧？反正也不可能
被发现的，只要不自爆，死不承认不就行了。既然你喜欢玩，那我就陪你玩玩，看看是谁吃亏。
** [2020-09-04 五 11:07] - 为什么丰都这里有这么多山洞啊！！！          :Life:
   信号也差得不行
** [2020-09-17 四 21:05] - 我无法掩盖想你的心                          :Life:
   我好想你啊!
** [2020-09-20 日 15:43] - 发挥想象力写一篇作文                        :Life:
   突然想到小时候的作文题目，发挥想象力写一篇作文，那时想的都是成为一个什么职业，随后去做什么事，
现在想的都是能挣多少多少钱，如何如何就能轻松的挣钱，果然我随着年龄的攀升是越来越爱做白日梦了。
** [2020-09-22 二 15:07] - 图书馆撑伞                                  :Life:
   咱们广财图书馆有个很有趣的现象，阳光照进图书馆后，大家都会拿伞遮挡住阳光，比起这样，我更愿意让阳光打在我的课本上。
** [2020-09-23 三 10:18] - 看书                                       :Study:
   一句话看不懂，看十遍真的有用么？不如换个角度看呢!
** [2020-09-23 三 19:32] - 杨泽霖                                      :Life:
   杨泽霖说想看我闪念。
** [2020-09-24 四 11:07] - 不是吧                                      :Life:
   不是吧不是吧真的是她么？
** [2020-09-24 四 11:14] - 好吧                                        :Life:
   好吧不是她，看走眼了
** [2020-09-24 四 12:52] - 困                                          :Life:
   昨晚没睡好，导致现在在图书馆里看书有些困。
   说起困这个话题，突然想描述一下困是一种什么感觉。
   困是预示你现在想要睡觉了，有关具体的大脑是如何让人感知到困的我不太了解，但是能描述困的感觉！
   当你感到困的时候，例如你在看书，当你看着看着感到困了，那你肯定专注度不够了，因为困会让你想睡觉，此时你的大脑可能就是在并发执行进程，一个进程在运行着阅读书籍程序，另一个进程就是让你想要睡觉程序，而像阅读书籍这种程序呢它最好是持续运行，否则其利用率就会大大降低，这就是为什么我说当你感到困时你的专注度就肯定会下降的原因了。再具体说一下由困引发的打瞌睡，其实打瞌睡有三种状态：
   - 第一种
	看书占70%而想睡觉占30%，每看小会书就会想睡觉，这时你的阅读书籍进程请求中断，这个中断处理程序的作用是让你不要打瞌睡，此时你就又清醒了一下，调整好姿态准备继续运行阅读书籍程序，是的由于清醒程序的时间片已经用完，坚持不了多久，你就又开始打瞌睡了。
   - 第二种
	 想睡觉占70%，看书占30%，每打一会瞌睡就看一会书，其原理跟第一种打瞌睡差不多，只不过置反了罢了。这种打瞌睡的方式会让你感到一会舒适，一会地狱，就像周末想睡懒觉的你被你妈每隔几分钟来叫醒一趟的你，所以这种方式打瞌睡是最不舒适的，因为书籍也一点都看不下去，睡觉也睡不好，有睡觉内感觉了结果又醒了，简直是太难受了！
   - 第三种
	 这种方式的打瞌睡就是已经眼睛已经完全闭上了，但是脑子里仍然想的是阅读书籍进程，唉可能这就是进程与进程之间的交往性吧~，这种感觉最奇妙，明明你能清晰的感知到自己睡着了，但是却又不想平常睡觉一样的深沉，你就像在醒着睡一样！身边的一切事物你都能感知到，真是神奇不是么？说明我们的大脑真的很强大，至少说其处理能力很强大，虽然是类似单核的CPU，但是其容量真的超大，通过一些碎片就能整理很多成体系的想法出来。可能这种打瞌睡的方式让人很舒服吧，毕竟终于能稍微专注与睡觉了不是么，但是！这种方式在处理打瞌睡进程后，身体会感到异常的疲惫，具体原因暂时未知，我猜想可能是因为打瞌睡本身就是一个优先级较高的进程，而平常睡觉前都会执行的调整睡姿等程序都没有运行的吧。

最后，本来还挺困的，现在突然不困了，从计算机系统的角度来想，当我想要打瞌睡时是不是只需要找一个优先级更高的进程就可以防止我打瞌睡了！但是凡是都有两面性啊，总是做一件事也不太好，毕竟一直写闪念的话那书都不用读了对么？

突然想到...大脑的中的进程是否存在自带程序的进程，这些进程是否比普通进程优先级高，反正目前我能想到的大脑自带进程就是做爱了，只有做爱才能让一切变成串行执行....
** [2020-09-25 五 18:29] - 便便                                        :Life:     
   便便有三种味道:
   - 别人拉的
	 奇臭无比
   - 自己拉时
	 毫无波澜
   - 自己拉完
	 奇臭无比
** [2020-09-26 六 14:45] - 新教徒                                     :Study:
   今天又帮助一位同学安装了ArchLinux，桌面使用的是KDE，希望他能好好用下去吧。
** [2020-09-26 六 15:04] - 彩虹猫                                      :Life:
   在图书馆看书，一直用Emasc播放彩虹猫的歌曲，真的好嗨啊！不过听久了之后甚至会觉得很平静。。
** [2020-09-26 六 15:12] - 擤鼻涕                                      :Life:
   真的是日了狗了，前两天睡觉空调温度太低了，导致我现在有些感冒，疯狂流鼻涕，难受死了。
   关键是我在图书馆啊喂！很尴尬。
** [2020-09-26 六 16:27] - 流鼻涕                                      :Life:
   我很想知道流鼻涕时到底要不要多喝水呢？我感觉多喝水只会让我流鼻涕的量更大!!!!
** [2020-10-07 三 16:36] - 腱鞘炎
   这两天打王者荣耀有些多，导致我的左手小拇指有些腱鞘炎了。
身为一个Emacs用户，居然都没有腱鞘炎，玩个王者荣耀倒是给我整了这一出，真是操蛋... 这说明那些职业选手也是挺难受的。
** [2020-10-12 一 08:29] - 我吐了                                      :Life:
   大三的某老师说话的语调怎么让人那么难受呢？
** [2020-10-16 五 10:32] - 我又来吐槽学校的教学方式了                 :Study:
   今年大三了，学校开了门Python课程，翻了翻书发现书中的知识点我已经全部掌握，但是我还是来听课了。
可笑的是老师在面对已经学了两年计算机课程的同学们却还是将安装Python和PyCharm开发工具讲了三节课，一节课近两小时。
果然教育才是成为百万富翁的道路!!!
** [2020-10-18 日 00:54] - 你与我的区别                                :Life:
   为什么视频时你可以做到你完全做你的事情，把我晾在一边呢？而我却做不到.
''
** [2020-10-24 六 14:25] - 1024程序员节日快乐!                         :Life:
   希望那些已经在岗位的前辈们今天能轻松些吧1
